# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# Very Good Analysis - Recommended lint rules for Flutter apps
# https://pub.dev/packages/very_good_analysis
include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    # Public facing API should be documented
    public_member_api_docs: false

    # Lines should not be longer than 80 characters
    # Consider increasing this if needed for your project
    lines_longer_than_80_chars: false

    # Allow single-member abstract interfaces for repository contracts
    one_member_abstracts: false

    # Allow ignore without doc (value objects use ID equality)
    document_ignores: false

    # Allow singleton pattern with static getter
    prefer_constructors_over_static_methods: false

    # Allow fire-and-forget for modals and UI
    discarded_futures: false
    unawaited_futures: false

    # Allow repetition for clarity in MultiProvider
    cascade_invocations: false

    # Allow setAuthProvider/setConfigProvider pattern
    use_setters_to_change_properties: false

    # Allow default case for future event types
    no_default_cases: false

    # Allow EdgeInsets.all(0)
    use_named_constants: false

    # Allow explicit null check for optional callbacks
    prefer_null_aware_method_calls: false

    # Allow positional bool in callbacks
    avoid_positional_boolean_parameters: false

    # Allow TODO format
    flutter_style_todos: false

    # Allow custom dependency order
    sort_pub_dependencies: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  plugins:
    - drift_dev

  errors:
    # Treat missing return as an error
    missing_return: error
    # Treat missing required parameter as an error
    missing_required_param: error
