import 'package:drift/drift.dart';

@DataClassName('ConfigData')
class ConfigTable extends Table {
  TextColumn get id => text()();
  TextColumn get serverUrl =>
      text().withDefault(const Constant('https://api.example.com'))();
  TextColumn get agentId => text().withDefault(const Constant(''))();
  TextColumn get authToken => text().nullable()();
  TextColumn get refreshToken => text().nullable()();
  TextColumn get authUsername => text().nullable()();
  TextColumn get authPassword => text().nullable()();
  TextColumn get driverName => text()();
  TextColumn get odbcDriverName => text().withDefault(const Constant(''))();
  TextColumn get connectionString => text()();
  TextColumn get username => text()();
  TextColumn get password => text().nullable()();
  TextColumn get databaseName => text()();
  TextColumn get host => text()();
  IntColumn get port => integer()();
  DateTimeColumn get createdAt => dateTime()();
  DateTimeColumn get updatedAt => dateTime()();

  @override
  Set<Column> get primaryKey => {id};
}

// AgentConfigDataSource interface is defined in agent_config_drift_database.dart
// where ConfigData (generated by Drift) is accessible via the .g.dart file
