import 'package:drift/drift.dart';

@DataClassName('ConfigData')
class ConfigTable extends Table {
  TextColumn get id => text()();
  TextColumn get serverUrl => text().withDefault(const Constant('https://api.example.com'))();
  TextColumn get agentId => text().withDefault(const Constant(''))();
  TextColumn get authToken => text().nullable()();
  TextColumn get refreshToken => text().nullable()();
  TextColumn get authUsername => text().nullable()();
  TextColumn get authPassword => text().nullable()();
  TextColumn get driverName => text()();
  TextColumn get odbcDriverName => text().withDefault(const Constant(''))();
  TextColumn get connectionString => text()();
  TextColumn get username => text()();
  TextColumn get password => text().nullable()();
  TextColumn get databaseName => text()();
  TextColumn get host => text()();
  IntColumn get port => integer()();
  TextColumn get nome => text().withDefault(const Constant(''))();
  TextColumn get nomeFantasia => text().withDefault(const Constant(''))();
  TextColumn get cnaeCnpjCpf => text().withDefault(const Constant(''))();
  TextColumn get telefone => text().withDefault(const Constant(''))();
  TextColumn get celular => text().withDefault(const Constant(''))();
  TextColumn get email => text().withDefault(const Constant(''))();
  TextColumn get endereco => text().withDefault(const Constant(''))();
  TextColumn get numeroEndereco => text().withDefault(const Constant(''))();
  TextColumn get bairro => text().withDefault(const Constant(''))();
  TextColumn get cep => text().withDefault(const Constant(''))();
  TextColumn get nomeMunicipio => text().withDefault(const Constant(''))();
  TextColumn get ufMunicipio => text().withDefault(const Constant(''))();
  TextColumn get observacao => text().withDefault(const Constant(''))();
  IntColumn get hubProfileVersion => integer().nullable()();
  TextColumn get hubProfileUpdatedAt => text().nullable()();
  DateTimeColumn get createdAt => dateTime()();
  DateTimeColumn get updatedAt => dateTime()();

  @override
  Set<Column> get primaryKey => {id};
}

@DataClassName('ClientTokenCacheData')
class ClientTokenCacheTable extends Table {
  TextColumn get id => text()();
  TextColumn get clientId => text()();
  BoolColumn get isRevoked => boolean().withDefault(const Constant(false))();
  IntColumn get version => integer().withDefault(const Constant(1))();
  TextColumn get agentId => text().nullable()();
  TextColumn get tokenValue => text().nullable()();
  DateTimeColumn get createdAt => dateTime()();
  DateTimeColumn get updatedAt => dateTime().nullable()();
  TextColumn get payloadJson => text().withDefault(const Constant('{}'))();
  BoolColumn get allTables => boolean().withDefault(const Constant(false))();
  BoolColumn get allViews => boolean().withDefault(const Constant(false))();
  BoolColumn get allPermissions => boolean().withDefault(const Constant(false))();
  TextColumn get rulesJson => text().withDefault(const Constant('[]'))();
  DateTimeColumn get syncedAt => dateTime()();
  TextColumn get tokenHash => text().withDefault(const Constant(''))();

  @override
  Set<Column> get primaryKey => {id};

  @override
  List<Set<Column>> get uniqueKeys => [
    {tokenHash},
  ];
}

// AgentConfigDataSource interface is defined in agent_config_drift_database.dart
// where ConfigData (generated by Drift) is accessible via the .g.dart file
