part of '../agent_actions_provider.dart';

extension AgentActionsProviderSaveSurface on AgentActionsProvider {
  Future<bool> saveCommandLineAction({
    required String name,
    required String command,
    String? actionId,
    String? description,
    String? workingDirectory,
    AgentActionState state = AgentActionState.needsValidation,
    AgentActionNotificationPolicy notificationPolicy = const AgentActionNotificationPolicy(),
    AgentActionRetryPolicy retryPolicy = const AgentActionRetryPolicy(),
    AgentActionTimeoutPolicy timeoutPolicy = const AgentActionTimeoutPolicy(),
    AgentActionEnvironmentPolicy environmentPolicy = const AgentActionEnvironmentPolicy(),
    AgentActionExitCodePolicy exitCodePolicy = const AgentActionExitCodePolicy(),
    AgentActionProcessPolicy processPolicy = const AgentActionProcessPolicy(),
    AgentActionLifecyclePolicy lifecyclePolicy = const AgentActionLifecyclePolicy(),
    AgentActionRemotePolicy remotePolicy = const AgentActionRemotePolicy(),
    AgentActionElevatedPolicy elevatedPolicy = const AgentActionElevatedPolicy(),
    AgentActionContextPolicy? contextPolicy,
    AgentActionPathChangePolicy? pathChangePolicy,
    AgentActionEncodingPolicy encodingPolicy = const AgentActionEncodingPolicy(),
    AgentActionCapturePolicy capturePolicy = const AgentActionCapturePolicy(),
    AgentActionQueuePolicy queuePolicy = const AgentActionQueuePolicy(),
    AgentActionPathPolicy pathPolicy = const AgentActionPathPolicy(),
  }) => _saveCoordinator.saveCommandLineAction(
    name: name,
    command: command,
    canSave: canSaveAction,
    actionId: actionId,
    description: description,
    workingDirectory: workingDirectory,
    options: buildAgentActionDefinitionSaveOptions(
      state: state,
      notificationPolicy: notificationPolicy,
      retryPolicy: retryPolicy,
      timeoutPolicy: timeoutPolicy,
      environmentPolicy: environmentPolicy,
      exitCodePolicy: exitCodePolicy,
      processPolicy: processPolicy,
      lifecyclePolicy: lifecyclePolicy,
      remotePolicy: remotePolicy,
      elevatedPolicy: elevatedPolicy,
      contextPolicy: contextPolicy,
      pathChangePolicy: pathChangePolicy,
      encodingPolicy: encodingPolicy,
      capturePolicy: capturePolicy,
      queuePolicy: queuePolicy,
      pathPolicy: pathPolicy,
    ),
  );

  Future<bool> saveExecutableAction({
    required String name,
    required String executablePath,
    required List<String> arguments,
    String? actionId,
    String? description,
    String? workingDirectory,
    AgentActionState state = AgentActionState.needsValidation,
    AgentActionNotificationPolicy notificationPolicy = const AgentActionNotificationPolicy(),
    AgentActionRetryPolicy retryPolicy = const AgentActionRetryPolicy(),
    AgentActionTimeoutPolicy timeoutPolicy = const AgentActionTimeoutPolicy(),
    AgentActionEnvironmentPolicy environmentPolicy = const AgentActionEnvironmentPolicy(),
    AgentActionExitCodePolicy exitCodePolicy = const AgentActionExitCodePolicy(),
    AgentActionProcessPolicy processPolicy = const AgentActionProcessPolicy(),
    AgentActionLifecyclePolicy lifecyclePolicy = const AgentActionLifecyclePolicy(),
    AgentActionRemotePolicy remotePolicy = const AgentActionRemotePolicy(),
    AgentActionElevatedPolicy elevatedPolicy = const AgentActionElevatedPolicy(),
    AgentActionContextPolicy? contextPolicy,
    AgentActionPathChangePolicy? pathChangePolicy,
    AgentActionEncodingPolicy encodingPolicy = const AgentActionEncodingPolicy(),
    AgentActionCapturePolicy capturePolicy = const AgentActionCapturePolicy(),
    AgentActionQueuePolicy queuePolicy = const AgentActionQueuePolicy(),
    AgentActionPathPolicy pathPolicy = const AgentActionPathPolicy(),
  }) => _saveCoordinator.saveExecutableAction(
    name: name,
    executablePath: executablePath,
    arguments: arguments,
    canSave: canSaveAction,
    actionId: actionId,
    description: description,
    workingDirectory: workingDirectory,
    options: buildAgentActionDefinitionSaveOptions(
      state: state,
      notificationPolicy: notificationPolicy,
      retryPolicy: retryPolicy,
      timeoutPolicy: timeoutPolicy,
      environmentPolicy: environmentPolicy,
      exitCodePolicy: exitCodePolicy,
      processPolicy: processPolicy,
      lifecyclePolicy: lifecyclePolicy,
      remotePolicy: remotePolicy,
      elevatedPolicy: elevatedPolicy,
      contextPolicy: contextPolicy,
      pathChangePolicy: pathChangePolicy,
      encodingPolicy: encodingPolicy,
      capturePolicy: capturePolicy,
      queuePolicy: queuePolicy,
      pathPolicy: pathPolicy,
    ),
  );

  Future<bool> saveScriptAction({
    required String name,
    required String scriptPath,
    required List<String> arguments,
    String? actionId,
    String? description,
    String? interpreterPath,
    String? workingDirectory,
    AgentActionState state = AgentActionState.needsValidation,
    AgentActionNotificationPolicy notificationPolicy = const AgentActionNotificationPolicy(),
    AgentActionRetryPolicy retryPolicy = const AgentActionRetryPolicy(),
    AgentActionTimeoutPolicy timeoutPolicy = const AgentActionTimeoutPolicy(),
    AgentActionEnvironmentPolicy environmentPolicy = const AgentActionEnvironmentPolicy(),
    AgentActionExitCodePolicy exitCodePolicy = const AgentActionExitCodePolicy(),
    AgentActionProcessPolicy processPolicy = const AgentActionProcessPolicy(),
    AgentActionLifecyclePolicy lifecyclePolicy = const AgentActionLifecyclePolicy(),
    AgentActionRemotePolicy remotePolicy = const AgentActionRemotePolicy(),
    AgentActionElevatedPolicy elevatedPolicy = const AgentActionElevatedPolicy(),
    AgentActionContextPolicy? contextPolicy,
    AgentActionPathChangePolicy? pathChangePolicy,
    AgentActionEncodingPolicy encodingPolicy = const AgentActionEncodingPolicy(),
    AgentActionCapturePolicy capturePolicy = const AgentActionCapturePolicy(),
    AgentActionQueuePolicy queuePolicy = const AgentActionQueuePolicy(),
    AgentActionPathPolicy pathPolicy = const AgentActionPathPolicy(),
  }) => _saveCoordinator.saveScriptAction(
    name: name,
    scriptPath: scriptPath,
    arguments: arguments,
    canSave: canSaveAction,
    actionId: actionId,
    description: description,
    interpreterPath: interpreterPath,
    workingDirectory: workingDirectory,
    options: buildAgentActionDefinitionSaveOptions(
      state: state,
      notificationPolicy: notificationPolicy,
      retryPolicy: retryPolicy,
      timeoutPolicy: timeoutPolicy,
      environmentPolicy: environmentPolicy,
      exitCodePolicy: exitCodePolicy,
      processPolicy: processPolicy,
      lifecyclePolicy: lifecyclePolicy,
      remotePolicy: remotePolicy,
      elevatedPolicy: elevatedPolicy,
      contextPolicy: contextPolicy,
      pathChangePolicy: pathChangePolicy,
      encodingPolicy: encodingPolicy,
      capturePolicy: capturePolicy,
      queuePolicy: queuePolicy,
      pathPolicy: pathPolicy,
    ),
  );

  Future<bool> saveJarAction({
    required String name,
    required String jarPath,
    required List<String> arguments,
    String? actionId,
    String? description,
    String? javaExecutablePath,
    String? workingDirectory,
    AgentActionState state = AgentActionState.needsValidation,
    AgentActionNotificationPolicy notificationPolicy = const AgentActionNotificationPolicy(),
    AgentActionRetryPolicy retryPolicy = const AgentActionRetryPolicy(),
    AgentActionTimeoutPolicy timeoutPolicy = const AgentActionTimeoutPolicy(),
    AgentActionEnvironmentPolicy environmentPolicy = const AgentActionEnvironmentPolicy(),
    AgentActionExitCodePolicy exitCodePolicy = const AgentActionExitCodePolicy(),
    AgentActionProcessPolicy processPolicy = const AgentActionProcessPolicy(),
    AgentActionLifecyclePolicy lifecyclePolicy = const AgentActionLifecyclePolicy(),
    AgentActionRemotePolicy remotePolicy = const AgentActionRemotePolicy(),
    AgentActionElevatedPolicy elevatedPolicy = const AgentActionElevatedPolicy(),
    AgentActionContextPolicy? contextPolicy,
    AgentActionPathChangePolicy? pathChangePolicy,
    AgentActionEncodingPolicy encodingPolicy = const AgentActionEncodingPolicy(),
    AgentActionCapturePolicy capturePolicy = const AgentActionCapturePolicy(),
    AgentActionQueuePolicy queuePolicy = const AgentActionQueuePolicy(),
    AgentActionPathPolicy pathPolicy = const AgentActionPathPolicy(),
  }) => _saveCoordinator.saveJarAction(
    name: name,
    jarPath: jarPath,
    arguments: arguments,
    canSave: canSaveAction,
    actionId: actionId,
    description: description,
    javaExecutablePath: javaExecutablePath,
    workingDirectory: workingDirectory,
    options: buildAgentActionDefinitionSaveOptions(
      state: state,
      notificationPolicy: notificationPolicy,
      retryPolicy: retryPolicy,
      timeoutPolicy: timeoutPolicy,
      environmentPolicy: environmentPolicy,
      exitCodePolicy: exitCodePolicy,
      processPolicy: processPolicy,
      lifecyclePolicy: lifecyclePolicy,
      remotePolicy: remotePolicy,
      elevatedPolicy: elevatedPolicy,
      contextPolicy: contextPolicy,
      pathChangePolicy: pathChangePolicy,
      encodingPolicy: encodingPolicy,
      capturePolicy: capturePolicy,
      queuePolicy: queuePolicy,
      pathPolicy: pathPolicy,
    ),
  );

  Future<bool> saveEmailAction({
    required String name,
    required String smtpProfileId,
    required String from,
    required List<String> to,
    required String subjectTemplate,
    required String bodyTemplate,
    String? actionId,
    String? description,
    List<String> cc = const <String>[],
    List<String> bcc = const <String>[],
    List<AgentActionPathReference> attachmentPaths = const <AgentActionPathReference>[],
    AgentActionState state = AgentActionState.needsValidation,
    AgentActionNotificationPolicy notificationPolicy = const AgentActionNotificationPolicy(),
    AgentActionRetryPolicy retryPolicy = const AgentActionRetryPolicy(),
    AgentActionTimeoutPolicy timeoutPolicy = const AgentActionTimeoutPolicy(),
    AgentActionEnvironmentPolicy environmentPolicy = const AgentActionEnvironmentPolicy(),
    AgentActionExitCodePolicy exitCodePolicy = const AgentActionExitCodePolicy(),
    AgentActionProcessPolicy processPolicy = const AgentActionProcessPolicy(),
    AgentActionLifecyclePolicy lifecyclePolicy = const AgentActionLifecyclePolicy(),
    AgentActionRemotePolicy remotePolicy = const AgentActionRemotePolicy(),
    AgentActionElevatedPolicy elevatedPolicy = const AgentActionElevatedPolicy(),
    AgentActionContextPolicy? contextPolicy,
    AgentActionPathChangePolicy? pathChangePolicy,
    AgentActionQueuePolicy queuePolicy = const AgentActionQueuePolicy(),
    AgentActionPathPolicy pathPolicy = const AgentActionPathPolicy(),
  }) => _saveCoordinator.saveEmailAction(
    name: name,
    smtpProfileId: smtpProfileId,
    from: from,
    to: to,
    subjectTemplate: subjectTemplate,
    bodyTemplate: bodyTemplate,
    canSave: canSaveAction,
    actionId: actionId,
    description: description,
    cc: cc,
    bcc: bcc,
    attachmentPaths: attachmentPaths,
    options: buildAgentActionDefinitionSaveOptions(
      state: state,
      notificationPolicy: notificationPolicy,
      retryPolicy: retryPolicy,
      timeoutPolicy: timeoutPolicy,
      environmentPolicy: environmentPolicy,
      exitCodePolicy: exitCodePolicy,
      processPolicy: processPolicy,
      lifecyclePolicy: lifecyclePolicy,
      remotePolicy: remotePolicy,
      elevatedPolicy: elevatedPolicy,
      contextPolicy: contextPolicy,
      pathChangePolicy: pathChangePolicy,
      queuePolicy: queuePolicy,
      pathPolicy: pathPolicy,
    ),
  );

  Future<bool> saveComObjectAction({
    required String name,
    required String progId,
    required String memberName,
    required Map<String, Object?> arguments,
    String? actionId,
    String? description,
    AgentActionState state = AgentActionState.needsValidation,
    AgentActionNotificationPolicy notificationPolicy = const AgentActionNotificationPolicy(),
    AgentActionRetryPolicy retryPolicy = const AgentActionRetryPolicy(),
    AgentActionTimeoutPolicy timeoutPolicy = const AgentActionTimeoutPolicy(),
    AgentActionEnvironmentPolicy environmentPolicy = const AgentActionEnvironmentPolicy(),
    AgentActionExitCodePolicy exitCodePolicy = const AgentActionExitCodePolicy(),
    AgentActionProcessPolicy processPolicy = const AgentActionProcessPolicy(),
    AgentActionLifecyclePolicy lifecyclePolicy = const AgentActionLifecyclePolicy(),
    AgentActionRemotePolicy remotePolicy = const AgentActionRemotePolicy(),
    AgentActionElevatedPolicy elevatedPolicy = const AgentActionElevatedPolicy(),
    AgentActionContextPolicy? contextPolicy,
    AgentActionPathChangePolicy? pathChangePolicy,
    AgentActionQueuePolicy queuePolicy = const AgentActionQueuePolicy(),
    AgentActionPathPolicy pathPolicy = const AgentActionPathPolicy(),
  }) => _saveCoordinator.saveComObjectAction(
    name: name,
    progId: progId,
    memberName: memberName,
    arguments: arguments,
    canSave: canSaveAction,
    actionId: actionId,
    description: description,
    options: buildAgentActionDefinitionSaveOptions(
      state: state,
      notificationPolicy: notificationPolicy,
      retryPolicy: retryPolicy,
      timeoutPolicy: timeoutPolicy,
      environmentPolicy: environmentPolicy,
      exitCodePolicy: exitCodePolicy,
      processPolicy: processPolicy,
      lifecyclePolicy: lifecyclePolicy,
      remotePolicy: remotePolicy,
      elevatedPolicy: elevatedPolicy,
      contextPolicy: contextPolicy,
      pathChangePolicy: pathChangePolicy,
      queuePolicy: queuePolicy,
      pathPolicy: pathPolicy,
    ),
  );

  Future<bool> saveDeveloperData7Action({
    required String name,
    required String executorPath,
    required String projectPath,
    required String connectionId,
    required String connectionLabel,
    String? actionId,
    String? description,
    String? data7ConfigPath,
    AgentActionState state = AgentActionState.needsValidation,
    AgentActionNotificationPolicy notificationPolicy = const AgentActionNotificationPolicy(),
    AgentActionRetryPolicy retryPolicy = const AgentActionRetryPolicy(),
    AgentActionTimeoutPolicy timeoutPolicy = const AgentActionTimeoutPolicy(),
    AgentActionEnvironmentPolicy environmentPolicy = const AgentActionEnvironmentPolicy(),
    AgentActionExitCodePolicy exitCodePolicy = const AgentActionExitCodePolicy(),
    AgentActionProcessPolicy processPolicy = const AgentActionProcessPolicy(),
    AgentActionLifecyclePolicy lifecyclePolicy = const AgentActionLifecyclePolicy(),
    AgentActionRemotePolicy remotePolicy = const AgentActionRemotePolicy(),
    AgentActionElevatedPolicy elevatedPolicy = const AgentActionElevatedPolicy(),
    AgentActionContextPolicy? contextPolicy,
    AgentActionPathChangePolicy? pathChangePolicy,
    AgentActionEncodingPolicy encodingPolicy = const AgentActionEncodingPolicy(),
    AgentActionCapturePolicy capturePolicy = const AgentActionCapturePolicy(),
    AgentActionQueuePolicy queuePolicy = const AgentActionQueuePolicy(),
    AgentActionPathPolicy pathPolicy = const AgentActionPathPolicy(),
  }) => _saveCoordinator.saveDeveloperData7Action(
    name: name,
    executorPath: executorPath,
    projectPath: projectPath,
    connectionId: connectionId,
    connectionLabel: connectionLabel,
    canSave: canSaveAction,
    actionId: actionId,
    description: description,
    data7ConfigPath: data7ConfigPath,
    options: buildAgentActionDefinitionSaveOptions(
      state: state,
      notificationPolicy: notificationPolicy,
      retryPolicy: retryPolicy,
      timeoutPolicy: timeoutPolicy,
      environmentPolicy: environmentPolicy,
      exitCodePolicy: exitCodePolicy,
      processPolicy: processPolicy,
      lifecyclePolicy: lifecyclePolicy,
      remotePolicy: remotePolicy,
      elevatedPolicy: elevatedPolicy,
      contextPolicy: contextPolicy,
      pathChangePolicy: pathChangePolicy,
      encodingPolicy: encodingPolicy,
      capturePolicy: capturePolicy,
      queuePolicy: queuePolicy,
      pathPolicy: pathPolicy,
    ),
  );
}
