import 'dart:async';
import 'dart:io';

import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:plug_agente/infrastructure/datasources/agent_config_data_source.dart';

part 'agent_config_drift_database.g.dart';

// ConfigData is generated by Drift in agent_config_drift_database.g.dart
abstract class AgentConfigDataSource {
  Future<List<ConfigData>> getAllConfigs();
  Future<ConfigData?> getConfigById(String id);
  Future<ConfigData?> getCurrentConfig();
  // Insertable<ConfigData> allows passing either ConfigData or ConfigTableCompanion
  Future<ConfigData> saveConfig(Insertable<ConfigData> config);
  Future<void> deleteConfig(String id);
}

@DriftDatabase(tables: [ConfigTable, ClientTokenCacheTable])
class AppDatabase extends _$AppDatabase implements AgentConfigDataSource {
  AppDatabase([QueryExecutor? executor]) : super(executor ?? _openConnection()) {
    _startWalMaintenance();
  }

  Timer? _walCheckpointTimer;
  static const _walCheckpointInterval = Duration(minutes: 5);

  @override
  int get schemaVersion => 9;

  @override
  MigrationStrategy get migration => MigrationStrategy(
    onCreate: (Migrator m) async {
      await m.createAll();
      await _createClientTokenIndexes();
    },
    onUpgrade: (Migrator m, int from, int to) async {
      if (from < 2) {
        await m.addColumn(configTable, configTable.serverUrl);
        await m.addColumn(configTable, configTable.agentId);
      }
      if (from < 3) {
        await m.addColumn(
          configTable,
          configTable.authToken as GeneratedColumn<Object>,
        );
        await m.addColumn(
          configTable,
          configTable.refreshToken as GeneratedColumn<Object>,
        );
      }
      if (from < 4) {
        await m.addColumn(
          configTable,
          configTable.authUsername as GeneratedColumn<Object>,
        );
        await m.addColumn(
          configTable,
          configTable.authPassword as GeneratedColumn<Object>,
        );
      }
      if (from < 5) {
        await m.alterTable(
          // ignore: experimental_member_use - TableMigration is Drift's API for column defaults
          TableMigration(
            configTable,
            columnTransformer: {configTable.odbcDriverName: const Constant('')},
            newColumns: [configTable.odbcDriverName],
          ),
        );
      }
      if (from < 6) {
        await m.createTable(clientTokenCacheTable);
      }
      if (from < 7) {
        await m.addColumn(
          clientTokenCacheTable,
          clientTokenCacheTable.tokenHash,
        );
      }
      if (from < 8) {
        await m.addColumn(
          clientTokenCacheTable,
          clientTokenCacheTable.tokenValue,
        );
      }
      if (from < 9) {
        await m.addColumn(clientTokenCacheTable, clientTokenCacheTable.version);
        await m.addColumn(
          clientTokenCacheTable,
          clientTokenCacheTable.updatedAt,
        );
        await customStatement(
          '''
          UPDATE client_token_cache_table
          SET updated_at = COALESCE(updated_at, synced_at, created_at)
          WHERE updated_at IS NULL
          ''',
        );
      }
      await _createClientTokenIndexes();
    },
    beforeOpen: (details) async {
      await customStatement('PRAGMA foreign_keys = ON');
      await customStatement('PRAGMA journal_mode = WAL');
      await customStatement('PRAGMA synchronous = NORMAL');
      await customStatement('PRAGMA busy_timeout = 5000');
      await customStatement('PRAGMA wal_autocheckpoint = 1000');
    },
  );

  Future<void> _createClientTokenIndexes() async {
    await customStatement(
      '''
      CREATE INDEX IF NOT EXISTS idx_client_token_client_created
      ON client_token_cache_table(client_id, created_at DESC)
      ''',
    );
    await customStatement(
      '''
      CREATE INDEX IF NOT EXISTS idx_client_token_status_created
      ON client_token_cache_table(is_revoked, created_at DESC)
      ''',
    );
  }

  @override
  Future<List<ConfigData>> getAllConfigs() => select(configTable).get();

  @override
  Future<ConfigData?> getConfigById(String id) => (select(
    configTable,
  )..where((tbl) => tbl.id.equals(id))).getSingleOrNull();

  @override
  Future<ConfigData?> getCurrentConfig() =>
      (select(configTable)
            ..orderBy([
              (tbl) => OrderingTerm(
                expression: tbl.updatedAt,
                mode: OrderingMode.desc,
              ),
            ])
            ..limit(1))
          .getSingleOrNull();

  @override
  Future<ConfigData> saveConfig(Insertable<ConfigData> config) async {
    await into(configTable).insertOnConflictUpdate(config);
    // After insertOnConflictUpdate, fetch the saved config by extracting ID
    if (config is ConfigData) {
      final saved = await getConfigById(config.id);
      return saved ?? config;
    }
    // If ConfigTableCompanion, get the ID and fetch
    final companion = config as ConfigTableCompanion;
    final id = companion.id.value;
    final saved = await getConfigById(id);
    if (saved == null) {
      throw StateError('Config saved but could not retrieve it');
    }
    return saved;
  }

  @override
  Future<void> deleteConfig(String id) => (delete(configTable)..where((tbl) => tbl.id.equals(id))).go();

  void _startWalMaintenance() {
    _walCheckpointTimer?.cancel();
    _walCheckpointTimer = Timer.periodic(_walCheckpointInterval, (_) {
      _runWalCheckpoint();
    });
  }

  Future<void> _runWalCheckpoint() async {
    try {
      await customStatement('PRAGMA wal_checkpoint(PASSIVE)');
    } on Exception {
      // Best effort maintenance task.
    }
  }

  @override
  Future<void> close() async {
    _walCheckpointTimer?.cancel();
    _walCheckpointTimer = null;
    await super.close();
  }
}

LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'agent_config.db'));
    return NativeDatabase(file);
  });
}
