import 'dart:async';
import 'dart:developer' as developer;
import 'dart:io';

import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:flutter/foundation.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:plug_agente/core/diagnostics/legacy_database_migration_status.dart';
import 'package:plug_agente/core/storage/global_storage_path_resolver.dart';
import 'package:plug_agente/core/utils/odbc_connection_string_secrets.dart';
import 'package:plug_agente/domain/repositories/i_odbc_credential_secret_store.dart';
import 'package:plug_agente/domain/value_objects/odbc_credential_secrets.dart';
import 'package:plug_agente/infrastructure/datasources/agent_config_data_source.dart';
import 'package:plug_agente/infrastructure/stores/flutter_secure_odbc_credential_secret_store.dart';
import 'package:sqlite3/sqlite3.dart' as sqlite;

part 'agent_config_drift_database.g.dart';
part 'migrations/agent_config_drift_migration_helpers.dart';
part 'migrations/agent_config_drift_on_upgrade.dart';
part 'migrations/migration_v02_to_v09.dart';
part 'migrations/migration_v10_to_v13.dart';
part 'migrations/migration_v14_to_v20.dart';
part 'migrations/migration_v21_to_v27.dart';
part 'migrations/migration_v28.dart';
part 'migrations/migration_v29.dart';
part 'migrations/migration_v30.dart';

// ConfigData is generated by Drift in agent_config_drift_database.g.dart
abstract class AgentConfigDataSource {
  Future<List<ConfigData>> getAllConfigs();
  Future<ConfigData?> getConfigById(String id);
  Future<ConfigData?> getCurrentConfig();
  // Insertable<ConfigData> allows passing either ConfigData or ConfigTableCompanion
  Future<ConfigData> saveConfig(Insertable<ConfigData> config);
  Future<void> deleteConfig(String id);
}

@DriftDatabase(
  tables: [
    ConfigTable,
    ClientTokenCacheTable,
    AgentActionDefinitionTable,
    AgentActionTriggerTable,
    AgentActionExecutionTable,
    RpcIdempotencyCacheTable,
    AgentActionRemoteAuditTable,
    AgentActionCapturedOutputChunkTable,
  ],
)
class AppDatabase extends _$AppDatabase with _AppDatabaseMigrationHelpers implements AgentConfigDataSource {
  AppDatabase({
    QueryExecutor? executor,
    String? databaseFilePath,
  }) : super(
         executor ??
             _openConnection(
               databaseFilePath: databaseFilePath,
             ),
       ) {
    _startWalMaintenance();
  }

  Timer? _walCheckpointTimer;
  static const _walCheckpointInterval = Duration(minutes: 5);

  @override
  int get schemaVersion => 30;

  @override
  MigrationStrategy get migration => MigrationStrategy(
    onCreate: (Migrator m) async {
      await m.createAll();
      await createClientTokenIndexes();
      await createAgentActionIndexes();
      await createRpcIdempotencyIndexes();
      await createAgentActionRemoteAuditIndexes();
      await createAgentActionCapturedOutputChunkIndexes();
    },
    onUpgrade: (Migrator m, int from, int to) async {
      await runAgentConfigDatabaseUpgrade(this, m, from, to);
    },
    beforeOpen: (details) async {
      await customStatement('PRAGMA foreign_keys = ON');
      await customStatement('PRAGMA journal_mode = WAL');
      await customStatement('PRAGMA synchronous = NORMAL');
      await customStatement('PRAGMA busy_timeout = 5000');
      await customStatement('PRAGMA wal_autocheckpoint = 1000');
    },
  );

  @override
  Future<List<ConfigData>> getAllConfigs() => select(configTable).get();

  @override
  Future<ConfigData?> getConfigById(String id) => (select(
    configTable,
  )..where((tbl) => tbl.id.equals(id))).getSingleOrNull();

  @override
  Future<ConfigData?> getCurrentConfig() =>
      (select(configTable)
            ..orderBy([
              (tbl) => OrderingTerm(
                expression: tbl.updatedAt,
                mode: OrderingMode.desc,
              ),
            ])
            ..limit(1))
          .getSingleOrNull();

  @override
  Future<ConfigData> saveConfig(Insertable<ConfigData> config) async {
    await into(configTable).insertOnConflictUpdate(config);
    // After insertOnConflictUpdate, fetch the saved config by extracting ID
    if (config is ConfigData) {
      final saved = await getConfigById(config.id);
      return saved ?? config;
    }
    // If ConfigTableCompanion, get the ID and fetch
    final companion = config as ConfigTableCompanion;
    final id = companion.id.value;
    final saved = await getConfigById(id);
    if (saved == null) {
      throw StateError('Config saved but could not retrieve it');
    }
    return saved;
  }

  @override
  Future<void> deleteConfig(String id) => (delete(configTable)..where((tbl) => tbl.id.equals(id))).go();

  void _startWalMaintenance() {
    _walCheckpointTimer?.cancel();
    _walCheckpointTimer = Timer.periodic(_walCheckpointInterval, (_) {
      _runWalCheckpoint();
    });
  }

  Future<void> _runWalCheckpoint() async {
    try {
      await customStatement('PRAGMA wal_checkpoint(PASSIVE)');
    } on Exception catch (e, stackTrace) {
      developer.log(
        'WAL checkpoint failed (best effort maintenance)',
        name: 'agent_config_drift_database',
        error: e,
        stackTrace: stackTrace,
      );
    }
  }

  @override
  Future<void> close() async {
    _walCheckpointTimer?.cancel();
    _walCheckpointTimer = null;
    await super.close();
  }
}

LazyDatabase _openConnection({
  String? databaseFilePath,
}) {
  return LazyDatabase(() async {
    final globalDirectoryPath = databaseFilePath != null
        ? File(databaseFilePath).parent.path
        : (await GlobalStoragePathResolver.resolveContext()).appDirectoryPath;
    final globalDir = Directory(globalDirectoryPath);
    try {
      if (!globalDir.existsSync()) {
        await globalDir.create(recursive: true);
      }
    } on FileSystemException catch (error) {
      throw GlobalStorageAccessException(
        message: 'Failed to create or access global database directory.',
        attempts: <String>['$globalDirectoryPath -> ${error.message}'],
      );
    }

    final file = File(
      databaseFilePath ?? p.join(globalDir.path, 'agent_config.db'),
    );
    await _migrateLegacyDatabaseIfNeeded(file);
    return NativeDatabase(file);
  });
}

Future<void> _migrateLegacyDatabaseIfNeeded(File globalDbFile) async {
  if (globalDbFile.existsSync()) {
    return;
  }

  try {
    final legacyFolder = await getApplicationDocumentsDirectory();
    final legacyDb = File(p.join(legacyFolder.path, 'agent_config.db'));
    if (!legacyDb.existsSync()) {
      return;
    }

    await _checkpointLegacySqliteIfPossible(legacyDb);
    await legacyDb.copy(globalDbFile.path);
    await _copySidecarFileIfExists(
      source: File('${legacyDb.path}-wal'),
      destination: File('${globalDbFile.path}-wal'),
    );
    await _copySidecarFileIfExists(
      source: File('${legacyDb.path}-shm'),
      destination: File('${globalDbFile.path}-shm'),
    );
  } on Exception catch (e, stackTrace) {
    final message = 'Legacy database migration failed: $e';
    LegacyDatabaseMigrationStatus.recordFailure(message);
    developer.log(
      message,
      name: 'agent_config_drift_database',
      level: 1000,
      error: e,
      stackTrace: stackTrace,
    );
  }
}

Future<void> _copySidecarFileIfExists({
  required File source,
  required File destination,
}) async {
  if (!source.existsSync()) {
    return;
  }
  await source.copy(destination.path);
}

Future<void> _checkpointLegacySqliteIfPossible(File legacyDb) async {
  try {
    final database = sqlite.sqlite3.open(legacyDb.path, mode: sqlite.OpenMode.readOnly);
    try {
      database.execute('PRAGMA wal_checkpoint(TRUNCATE);');
    } finally {
      database.dispose();
    }
  } on Object catch (error, stackTrace) {
    developer.log(
      'Legacy database WAL checkpoint failed before migration copy; continuing with file copy',
      name: 'agent_config_drift_database',
      level: 900,
      error: error,
      stackTrace: stackTrace,
    );
  }
}
