import 'dart:async';
import 'dart:developer' as developer;
import 'dart:io';

import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:plug_agente/core/storage/global_storage_path_resolver.dart';
import 'package:plug_agente/infrastructure/datasources/agent_config_data_source.dart';

part 'agent_config_drift_database.g.dart';

// ConfigData is generated by Drift in agent_config_drift_database.g.dart
abstract class AgentConfigDataSource {
  Future<List<ConfigData>> getAllConfigs();
  Future<ConfigData?> getConfigById(String id);
  Future<ConfigData?> getCurrentConfig();
  // Insertable<ConfigData> allows passing either ConfigData or ConfigTableCompanion
  Future<ConfigData> saveConfig(Insertable<ConfigData> config);
  Future<void> deleteConfig(String id);
}

@DriftDatabase(
  tables: [
    ConfigTable,
    ClientTokenCacheTable,
    AgentActionDefinitionTable,
    AgentActionTriggerTable,
    AgentActionExecutionTable,
    RpcIdempotencyCacheTable,
    AgentActionRemoteAuditTable,
    AgentActionCapturedOutputChunkTable,
  ],
)
class AppDatabase extends _$AppDatabase implements AgentConfigDataSource {
  AppDatabase({
    QueryExecutor? executor,
    String? databaseFilePath,
  }) : super(
         executor ??
             _openConnection(
               databaseFilePath: databaseFilePath,
             ),
       ) {
    _startWalMaintenance();
  }

  Timer? _walCheckpointTimer;
  static const _walCheckpointInterval = Duration(minutes: 5);

  @override
  int get schemaVersion => 28;

  @override
  MigrationStrategy get migration => MigrationStrategy(
    onCreate: (Migrator m) async {
      await m.createAll();
      await _createClientTokenIndexes();
      await _createAgentActionIndexes();
      await _createRpcIdempotencyIndexes();
      await _createAgentActionRemoteAuditIndexes();
      await _createAgentActionCapturedOutputChunkIndexes();
    },
    onUpgrade: (Migrator m, int from, int to) async {
      if (from < 2) {
        await m.addColumn(configTable, configTable.serverUrl);
        await m.addColumn(configTable, configTable.agentId);
      }
      if (from < 3) {
        await m.addColumn(
          configTable,
          configTable.authToken as GeneratedColumn<Object>,
        );
        await m.addColumn(
          configTable,
          configTable.refreshToken as GeneratedColumn<Object>,
        );
      }
      if (from < 4) {
        await m.addColumn(
          configTable,
          configTable.authUsername as GeneratedColumn<Object>,
        );
        await m.addColumn(
          configTable,
          configTable.authPassword as GeneratedColumn<Object>,
        );
      }
      if (from < 5) {
        await m.alterTable(
          // ignore: experimental_member_use - TableMigration is Drift's API for column defaults
          TableMigration(
            configTable,
            columnTransformer: {configTable.odbcDriverName: const Constant('')},
            newColumns: [configTable.odbcDriverName],
          ),
        );
      }
      if (from < 6) {
        await m.createTable(clientTokenCacheTable);
      }
      if (from < 7) {
        await m.addColumn(
          clientTokenCacheTable,
          clientTokenCacheTable.tokenHash,
        );
      }
      if (from < 8) {
        await m.addColumn(
          clientTokenCacheTable,
          clientTokenCacheTable.tokenValue,
        );
      }
      if (from < 9) {
        await m.addColumn(clientTokenCacheTable, clientTokenCacheTable.version);
        await m.addColumn(
          clientTokenCacheTable,
          clientTokenCacheTable.updatedAt,
        );
        await customStatement(
          '''
          UPDATE client_token_cache_table
          SET updated_at = COALESCE(updated_at, synced_at, created_at)
          WHERE updated_at IS NULL
          ''',
        );
      }
      if (from < 10) {
        await _addAgentProfileColumnsIfMissing(m);
      }
      if (from < 11) {
        await m.addColumn(
          configTable,
          configTable.hubProfileVersion as GeneratedColumn<Object>,
        );
        await m.addColumn(
          configTable,
          configTable.hubProfileUpdatedAt as GeneratedColumn<Object>,
        );
      }
      if (from < 12) {
        await _addClientTokenNameColumnIfMissing(m);
      }
      if (from < 13) {
        await _addClientTokenGlobalPermissionsColumnIfMissing(m);
        await customStatement(
          '''
          UPDATE client_token_cache_table
          SET global_permissions_json = CASE
            WHEN all_permissions = 1 THEN '{"read":true,"update":true,"delete":true,"ddl":true}'
            WHEN all_tables = 1 OR all_views = 1 THEN '{"read":true,"update":true,"delete":true,"ddl":false}'
            ELSE '{"read":false,"update":false,"delete":false,"ddl":false}'
          END
          WHERE global_permissions_json IS NULL
             OR TRIM(global_permissions_json) = ''
             OR global_permissions_json = '{"read":false,"update":false,"delete":false,"ddl":false}'
          ''',
        );
        await customStatement(
          '''
          UPDATE client_token_cache_table
          SET all_tables = 1,
              all_views = 1,
              all_permissions = 1,
              global_permissions_json = '{"read":true,"update":true,"delete":true,"ddl":true}'
          WHERE all_permissions = 1
          ''',
        );
      }
      // Agent action tables are additive-only: never drop or recreate them on upgrade.
      // Failed migrations follow the global Drift policy (app startup fails safely).
      if (from < 14) {
        await m.createTable(agentActionDefinitionTable);
        await m.createTable(agentActionExecutionTable);
      }
      if (from < 15) {
        await m.createTable(agentActionTriggerTable);
      }
      if (from < 16) {
        await _addAgentActionExecutionTriggerColumnsIfMissing(m);
      }
      if (from < 17) {
        await _addAgentActionExecutionProcessIdentityColumnsIfMissing(m);
      }
      if (from < 18) {
        await _addAgentActionExecutionFailurePhaseColumnIfMissing(m);
      }
      if (from < 19) {
        await m.createTable(rpcIdempotencyCacheTable);
      }
      if (from < 20) {
        await m.createTable(agentActionRemoteAuditTable);
      }
      if (from < 21) {
        await _addAgentActionExecutionRuntimeIdentityColumnsIfMissing(m);
      }
      if (from < 22) {
        await _addAgentActionRemoteAuditClientColumnsIfMissing(m);
      }
      if (from < 23) {
        await _addAgentActionRemoteAuditRuntimeIdentityColumnsIfMissing(m);
      }
      if (from < 24) {
        await _addAgentActionRemoteAuditIdempotencyKeyColumnIfMissing(m);
      }
      if (from < 25) {
        await m.createTable(agentActionCapturedOutputChunkTable);
        await _addAgentActionExecutionCapturedOutputChunkColumnsIfMissing(m);
      }
      if (from < 26) {
        await _addAgentActionDefinitionLastPreflightSnapshotHashColumnIfMissing(m);
      }
      if (from < 27) {
        await _addAgentActionDefinitionLastPreflightValidatedAtColumnIfMissing(m);
      }
      if (from < 28) {
        // Recreate AgentActionTriggerTable and AgentActionCapturedOutputChunkTable
        // to add REFERENCES (FK) constraints. TableMigration copies data and
        // recreates the table with the updated schema.
        // AgentActionExecutionTable.actionId is intentionally left without a FK
        // to preserve execution history after definition deletion (enforced at
        // the repository level in deleteDefinition).
        // ignore: experimental_member_use - TableMigration is Drift's API for table recreation
        await m.alterTable(TableMigration(agentActionTriggerTable));
        // ignore: experimental_member_use
        await m.alterTable(TableMigration(agentActionCapturedOutputChunkTable));
      }
      await _createClientTokenIndexes();
      await _createAgentActionIndexes();
      await _createRpcIdempotencyIndexes();
      await _createAgentActionRemoteAuditIndexes();
      await _createAgentActionCapturedOutputChunkIndexes();
    },
    beforeOpen: (details) async {
      await customStatement('PRAGMA foreign_keys = ON');
      await customStatement('PRAGMA journal_mode = WAL');
      await customStatement('PRAGMA synchronous = NORMAL');
      await customStatement('PRAGMA busy_timeout = 5000');
      await customStatement('PRAGMA wal_autocheckpoint = 1000');
    },
  );

  /// Adds profile columns only when missing. Handles databases where columns
  /// were already applied (e.g. partial migration or out-of-sync user_version)
  /// while the schema version is still below 10.
  Future<void> _addAgentProfileColumnsIfMissing(Migrator m) async {
    final existing = await _readConfigTableColumnNames();
    final profileColumns = <GeneratedColumn<Object>>[
      configTable.nome as GeneratedColumn<Object>,
      configTable.nomeFantasia as GeneratedColumn<Object>,
      configTable.cnaeCnpjCpf as GeneratedColumn<Object>,
      configTable.telefone as GeneratedColumn<Object>,
      configTable.celular as GeneratedColumn<Object>,
      configTable.email as GeneratedColumn<Object>,
      configTable.endereco as GeneratedColumn<Object>,
      configTable.numeroEndereco as GeneratedColumn<Object>,
      configTable.bairro as GeneratedColumn<Object>,
      configTable.cep as GeneratedColumn<Object>,
      configTable.nomeMunicipio as GeneratedColumn<Object>,
      configTable.ufMunicipio as GeneratedColumn<Object>,
      configTable.observacao as GeneratedColumn<Object>,
    ];
    for (final column in profileColumns) {
      final sqlName = column.name;
      if (existing.contains(sqlName)) {
        continue;
      }
      await m.addColumn(configTable, column);
      existing.add(sqlName);
    }
  }

  Future<Set<String>> _readConfigTableColumnNames() async {
    final rows = await customSelect(
      'PRAGMA table_info("config_table")',
      readsFrom: {configTable},
    ).get();
    return {for (final row in rows) row.read<String>('name')};
  }

  Future<void> _addClientTokenNameColumnIfMissing(Migrator m) async {
    final existing = await _readClientTokenTableColumnNames();
    final sqlName = clientTokenCacheTable.name.name;
    if (existing.contains(sqlName)) {
      return;
    }
    await m.addColumn(clientTokenCacheTable, clientTokenCacheTable.name);
  }

  Future<void> _addClientTokenGlobalPermissionsColumnIfMissing(
    Migrator m,
  ) async {
    final existing = await _readClientTokenTableColumnNames();
    final sqlName = clientTokenCacheTable.globalPermissionsJson.name;
    if (existing.contains(sqlName)) {
      return;
    }
    await m.addColumn(
      clientTokenCacheTable,
      clientTokenCacheTable.globalPermissionsJson,
    );
  }

  Future<Set<String>> _readClientTokenTableColumnNames() async {
    final rows = await customSelect(
      'PRAGMA table_info("client_token_cache_table")',
      readsFrom: {clientTokenCacheTable},
    ).get();
    return {for (final row in rows) row.read<String>('name')};
  }

  Future<void> _addAgentActionExecutionTriggerColumnsIfMissing(
    Migrator m,
  ) async {
    final existing = await _readAgentActionExecutionTableColumnNames();
    final triggerColumns = <GeneratedColumn<Object>>[
      agentActionExecutionTable.triggerId as GeneratedColumn<Object>,
      agentActionExecutionTable.triggerType as GeneratedColumn<Object>,
      agentActionExecutionTable.scheduledAt as GeneratedColumn<Object>,
      agentActionExecutionTable.triggeredAt as GeneratedColumn<Object>,
    ];
    for (final column in triggerColumns) {
      final sqlName = column.name;
      if (existing.contains(sqlName)) {
        continue;
      }
      await m.addColumn(agentActionExecutionTable, column);
      existing.add(sqlName);
    }
  }

  Future<void> _addAgentActionExecutionProcessIdentityColumnsIfMissing(
    Migrator m,
  ) async {
    final existing = await _readAgentActionExecutionTableColumnNames();
    final identityColumns = <GeneratedColumn<Object>>[
      agentActionExecutionTable.processExecutable as GeneratedColumn<Object>,
      agentActionExecutionTable.processArgumentCount as GeneratedColumn<Object>,
      agentActionExecutionTable.processCommandPreview as GeneratedColumn<Object>,
    ];
    for (final column in identityColumns) {
      final sqlName = column.name;
      if (existing.contains(sqlName)) {
        continue;
      }
      await m.addColumn(agentActionExecutionTable, column);
      existing.add(sqlName);
    }
  }

  Future<void> _addAgentActionExecutionFailurePhaseColumnIfMissing(
    Migrator m,
  ) async {
    final existing = await _readAgentActionExecutionTableColumnNames();
    final failurePhaseColumn = agentActionExecutionTable.failurePhase as GeneratedColumn<Object>;
    final sqlName = failurePhaseColumn.name;
    if (!existing.contains(sqlName)) {
      await m.addColumn(agentActionExecutionTable, failurePhaseColumn);
    }
  }

  Future<void> _addAgentActionDefinitionLastPreflightSnapshotHashColumnIfMissing(
    Migrator m,
  ) async {
    final existing = await _readAgentActionDefinitionTableColumnNames();
    final column = agentActionDefinitionTable.lastPreflightSnapshotHash;
    final sqlName = column.name;
    if (!existing.contains(sqlName)) {
      await m.addColumn(agentActionDefinitionTable, column);
    }
  }

  Future<void> _addAgentActionDefinitionLastPreflightValidatedAtColumnIfMissing(
    Migrator m,
  ) async {
    final existing = await _readAgentActionDefinitionTableColumnNames();
    final column = agentActionDefinitionTable.lastPreflightValidatedAt;
    final sqlName = column.name;
    if (!existing.contains(sqlName)) {
      await m.addColumn(agentActionDefinitionTable, column);
    }
  }

  Future<Set<String>> _readAgentActionDefinitionTableColumnNames() async {
    final rows = await customSelect(
      'PRAGMA table_info("agent_action_definition_table")',
      readsFrom: {agentActionDefinitionTable},
    ).get();
    return {for (final row in rows) row.read<String>('name')};
  }

  Future<void> _addAgentActionExecutionRuntimeIdentityColumnsIfMissing(
    Migrator m,
  ) async {
    final existing = await _readAgentActionExecutionTableColumnNames();
    final columns = <GeneratedColumn<Object>>[
      agentActionExecutionTable.runtimeInstanceId as GeneratedColumn<Object>,
      agentActionExecutionTable.runtimeSessionId as GeneratedColumn<Object>,
    ];
    for (final column in columns) {
      final sqlName = column.name;
      if (existing.contains(sqlName)) {
        continue;
      }
      await m.addColumn(agentActionExecutionTable, column);
      existing.add(sqlName);
    }
  }

  Future<Set<String>> _readAgentActionExecutionTableColumnNames() async {
    final rows = await customSelect(
      'PRAGMA table_info("agent_action_execution_table")',
      readsFrom: {agentActionExecutionTable},
    ).get();
    return {for (final row in rows) row.read<String>('name')};
  }

  Future<void> _addAgentActionExecutionCapturedOutputChunkColumnsIfMissing(
    Migrator m,
  ) async {
    final existing = await _readAgentActionExecutionTableColumnNames();
    final columns = <GeneratedColumn<Object>>[
      agentActionExecutionTable.stdoutStoredInChunks as GeneratedColumn<Object>,
      agentActionExecutionTable.stderrStoredInChunks as GeneratedColumn<Object>,
    ];
    for (final column in columns) {
      final sqlName = column.name;
      if (existing.contains(sqlName)) {
        continue;
      }
      await m.addColumn(agentActionExecutionTable, column);
      existing.add(sqlName);
    }
  }

  Future<Set<String>> _readAgentActionRemoteAuditTableColumnNames() async {
    final rows = await customSelect(
      'PRAGMA table_info("agent_action_remote_audit_table")',
      readsFrom: {agentActionRemoteAuditTable},
    ).get();
    return {for (final row in rows) row.read<String>('name')};
  }

  Future<void> _addAgentActionRemoteAuditClientColumnsIfMissing(Migrator m) async {
    var existing = await _readAgentActionRemoteAuditTableColumnNames();
    final columns = <GeneratedColumn<Object>>[
      agentActionRemoteAuditTable.clientId as GeneratedColumn<Object>,
      agentActionRemoteAuditTable.tokenJti as GeneratedColumn<Object>,
    ];
    for (final column in columns) {
      final sqlName = column.name;
      if (existing.contains(sqlName)) {
        continue;
      }
      await m.addColumn(agentActionRemoteAuditTable, column);
      existing = {...existing, sqlName};
    }
  }

  Future<void> _addAgentActionRemoteAuditRuntimeIdentityColumnsIfMissing(
    Migrator m,
  ) async {
    var existing = await _readAgentActionRemoteAuditTableColumnNames();
    final columns = <GeneratedColumn<Object>>[
      agentActionRemoteAuditTable.runtimeInstanceId as GeneratedColumn<Object>,
      agentActionRemoteAuditTable.runtimeSessionId as GeneratedColumn<Object>,
    ];
    for (final column in columns) {
      final sqlName = column.name;
      if (existing.contains(sqlName)) {
        continue;
      }
      await m.addColumn(agentActionRemoteAuditTable, column);
      existing = {...existing, sqlName};
    }
  }

  Future<void> _addAgentActionRemoteAuditIdempotencyKeyColumnIfMissing(Migrator m) async {
    final existing = await _readAgentActionRemoteAuditTableColumnNames();
    final column = agentActionRemoteAuditTable.idempotencyKey as GeneratedColumn<Object>;
    if (existing.contains(column.name)) {
      return;
    }
    await m.addColumn(agentActionRemoteAuditTable, column);
  }

  Future<void> _createRpcIdempotencyIndexes() async {
    await customStatement(
      '''
      CREATE INDEX IF NOT EXISTS idx_rpc_idempotency_expires
      ON rpc_idempotency_cache_table(expires_at)
      ''',
    );
  }

  Future<void> _createAgentActionRemoteAuditIndexes() async {
    await customStatement(
      '''
      CREATE INDEX IF NOT EXISTS idx_agent_action_remote_audit_occurred
      ON agent_action_remote_audit_table(occurred_at DESC)
      ''',
    );
    await customStatement(
      '''
      CREATE INDEX IF NOT EXISTS idx_agent_action_remote_audit_method_occurred
      ON agent_action_remote_audit_table(rpc_method, occurred_at DESC)
      ''',
    );
  }

  Future<void> _createClientTokenIndexes() async {
    await customStatement(
      '''
      CREATE INDEX IF NOT EXISTS idx_client_token_client_created
      ON client_token_cache_table(client_id, created_at DESC)
      ''',
    );
    await customStatement(
      '''
      CREATE INDEX IF NOT EXISTS idx_client_token_status_created
      ON client_token_cache_table(is_revoked, created_at DESC)
      ''',
    );
  }

  Future<void> _createAgentActionCapturedOutputChunkIndexes() async {
    await customStatement(
      '''
      CREATE INDEX IF NOT EXISTS idx_agent_action_captured_output_execution_stream
      ON agent_action_captured_output_chunk_table(execution_id, stream, chunk_index)
      ''',
    );
  }

  Future<void> _createAgentActionIndexes() async {
    await customStatement(
      '''
      CREATE INDEX IF NOT EXISTS idx_agent_action_definition_type_state
      ON agent_action_definition_table(type, state)
      ''',
    );
    await customStatement(
      '''
      CREATE INDEX IF NOT EXISTS idx_agent_action_execution_action_requested
      ON agent_action_execution_table(action_id, requested_at DESC)
      ''',
    );
    await customStatement(
      '''
      CREATE INDEX IF NOT EXISTS idx_agent_action_execution_status_requested
      ON agent_action_execution_table(status, requested_at DESC)
      ''',
    );
    await customStatement(
      '''
      CREATE INDEX IF NOT EXISTS idx_agent_action_execution_idempotency
      ON agent_action_execution_table(idempotency_key)
      WHERE idempotency_key IS NOT NULL
      ''',
    );
    await customStatement(
      '''
      CREATE INDEX IF NOT EXISTS idx_agent_action_execution_trigger
      ON agent_action_execution_table(trigger_id, scheduled_at)
      WHERE trigger_id IS NOT NULL
      ''',
    );
    await customStatement(
      '''
      CREATE INDEX IF NOT EXISTS idx_agent_action_trigger_action_enabled
      ON agent_action_trigger_table(action_id, is_enabled)
      ''',
    );
    await customStatement(
      '''
      CREATE INDEX IF NOT EXISTS idx_agent_action_trigger_type_next
      ON agent_action_trigger_table(type, next_run_at)
      ''',
    );
  }

  @override
  Future<List<ConfigData>> getAllConfigs() => select(configTable).get();

  @override
  Future<ConfigData?> getConfigById(String id) => (select(
    configTable,
  )..where((tbl) => tbl.id.equals(id))).getSingleOrNull();

  @override
  Future<ConfigData?> getCurrentConfig() =>
      (select(configTable)
            ..orderBy([
              (tbl) => OrderingTerm(
                expression: tbl.updatedAt,
                mode: OrderingMode.desc,
              ),
            ])
            ..limit(1))
          .getSingleOrNull();

  @override
  Future<ConfigData> saveConfig(Insertable<ConfigData> config) async {
    await into(configTable).insertOnConflictUpdate(config);
    // After insertOnConflictUpdate, fetch the saved config by extracting ID
    if (config is ConfigData) {
      final saved = await getConfigById(config.id);
      return saved ?? config;
    }
    // If ConfigTableCompanion, get the ID and fetch
    final companion = config as ConfigTableCompanion;
    final id = companion.id.value;
    final saved = await getConfigById(id);
    if (saved == null) {
      throw StateError('Config saved but could not retrieve it');
    }
    return saved;
  }

  @override
  Future<void> deleteConfig(String id) => (delete(configTable)..where((tbl) => tbl.id.equals(id))).go();

  void _startWalMaintenance() {
    _walCheckpointTimer?.cancel();
    _walCheckpointTimer = Timer.periodic(_walCheckpointInterval, (_) {
      _runWalCheckpoint();
    });
  }

  Future<void> _runWalCheckpoint() async {
    try {
      await customStatement('PRAGMA wal_checkpoint(PASSIVE)');
    } on Exception catch (e, stackTrace) {
      developer.log(
        'WAL checkpoint failed (best effort maintenance)',
        name: 'agent_config_drift_database',
        error: e,
        stackTrace: stackTrace,
      );
    }
  }

  @override
  Future<void> close() async {
    _walCheckpointTimer?.cancel();
    _walCheckpointTimer = null;
    await super.close();
  }
}

LazyDatabase _openConnection({
  String? databaseFilePath,
}) {
  return LazyDatabase(() async {
    final globalDirectoryPath = databaseFilePath != null
        ? File(databaseFilePath).parent.path
        : (await GlobalStoragePathResolver.resolveContext()).appDirectoryPath;
    final globalDir = Directory(globalDirectoryPath);
    try {
      if (!globalDir.existsSync()) {
        await globalDir.create(recursive: true);
      }
    } on FileSystemException catch (error) {
      throw GlobalStorageAccessException(
        message: 'Failed to create or access global database directory.',
        attempts: <String>['$globalDirectoryPath -> ${error.message}'],
      );
    }

    final file = File(
      databaseFilePath ?? p.join(globalDir.path, 'agent_config.db'),
    );
    await _migrateLegacyDatabaseIfNeeded(file);
    return NativeDatabase(file);
  });
}

Future<void> _migrateLegacyDatabaseIfNeeded(File globalDbFile) async {
  if (globalDbFile.existsSync()) {
    return;
  }

  try {
    final legacyFolder = await getApplicationDocumentsDirectory();
    final legacyDb = File(p.join(legacyFolder.path, 'agent_config.db'));
    if (!legacyDb.existsSync()) {
      return;
    }

    await legacyDb.copy(globalDbFile.path);
    await _copySidecarFileIfExists(
      source: File('${legacyDb.path}-wal'),
      destination: File('${globalDbFile.path}-wal'),
    );
    await _copySidecarFileIfExists(
      source: File('${legacyDb.path}-shm'),
      destination: File('${globalDbFile.path}-shm'),
    );
  } on Exception catch (e, stackTrace) {
    developer.log(
      'Legacy database migration failed (best effort)',
      name: 'agent_config_drift_database',
      error: e,
      stackTrace: stackTrace,
    );
  }
}

Future<void> _copySidecarFileIfExists({
  required File source,
  required File destination,
}) async {
  if (!source.existsSync()) {
    return;
  }
  await source.copy(destination.path);
}
