#!/usr/bin/env python3
"""
Synchronize the pubspec.yaml version into installer/setup.iss and lib/core/constants/app_version.g.dart.

Updates:
- installer/setup.iss: MyAppVersion (short: 1.0.11)
- lib/core/constants/app_version.g.dart: appVersion (full: 1.0.11+12)

Run from project root:
  python installer/update_version.py
"""

import re
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
PUBSPEC = PROJECT_ROOT / "pubspec.yaml"
SETUP_ISS = PROJECT_ROOT / "installer" / "setup.iss"
APP_VERSION_DART = PROJECT_ROOT / "lib" / "core" / "constants" / "app_version.g.dart"


def get_version_from_pubspec() -> tuple[str, str]:
    content = PUBSPEC.read_text(encoding="utf-8")
    match = re.search(
        r'^version:\s*["\']?([\d.]+(?:\+\d+)?)["\']?\s*(?:#|$)',
        content,
        re.MULTILINE,
    )
    if not match:
        raise SystemExit("Error: version not found in pubspec.yaml")
    full_version = match.group(1).strip()
    short_version = full_version.split("+")[0]
    return short_version, full_version


def update_setup_iss(version: str) -> None:
    content = SETUP_ISS.read_text(encoding="utf-8")
    new_content = re.sub(
        r'#define MyAppVersion\s+".*"',
        f'#define MyAppVersion "{version}"',
        content,
    )
    SETUP_ISS.write_text(new_content, encoding="utf-8")
    print(f"  setup.iss: MyAppVersion = {version}")


def update_app_version_dart(full_version: str) -> None:
    content = f'''// Generated by installer/update_version.py - do not edit manually.
const String appVersion = "{full_version}";
'''
    APP_VERSION_DART.parent.mkdir(parents=True, exist_ok=True)
    APP_VERSION_DART.write_text(content, encoding="utf-8")
    print(f"  app_version.g.dart: appVersion = {full_version}")


def main() -> None:
    short_version, full_version = get_version_from_pubspec()
    print(f"pubspec.yaml version: {full_version}")
    update_setup_iss(short_version)
    update_app_version_dart(full_version)
    print("Synchronization completed.")


if __name__ == "__main__":
    main()
